apiVersion: clinic.hasteward.prplanit.com/v1alpha1
kind: BackupPolicy
metadata:
  name: default
spec:
  backupSchedule: "0 0 2 * * *"
  triageSchedule: "0 */15 * * * *"
  mode: repair
  retention:
    keepLast: 7
    keepDaily: 30
    keepWeekly: 12
    keepMonthly: 24
  repositories:
    - local
    - s3
  healTimeout: 600
  deleteTimeout: 300
