apiVersion: v1
kind: Service
metadata:
  name: hasteward
  labels:
    app.kubernetes.io/name: hasteward
    app.kubernetes.io/component: operator
spec:
  selector:
    app.kubernetes.io/name: hasteward
    app.kubernetes.io/component: operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
